---
title: "ClusterID RFP res0.8 clusters R Notebook"
output: html_notebook
---

output: 
  html_notebook:
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
---

# 1. libraries and functions
```{r, results=F}
suppressPackageStartupMessages({
  library(Seurat)
  library(org.Dr.eg.db)
  library(BSgenome.Drerio.UCSC.danRer11)
  library(Signac)
  library(knitr)
  library(kableExtra)
  library(dplyr)
  library(ggplot2)
  library(ggsci)
  library(limma)
  library(JASPAR2020)
  library(patchwork)
  library(TFBSTools)
  library(motifmatchr)
  library(harmony)
})
options(future.globals.maxSize = 4000 * 1024^2)
```

```{r}
mypal <- pal_igv(palette = "default",alpha = 1)(50)
```

# 2. Read data
```{r}
seurat <- readRDS(file = "RDSfiles/RFP.clustered.RDS")
```

```{r}
DimPlot(seurat, reduction = "wnn.umap", group.by =  "wsnn_res.0.8", split.by = "orig.ident", label = T, repel = T) + scale_color_igv() + NoLegend()
```

# 3. Rename Clusters
```{r}
Idents(seurat) <- "wsnn_res.0.8"
seurat <- RenameIdents(seurat,
                       "0" = "CaudHB",
                       "1" = "Somite",
                       "2" = "Placode1",
                       "3" = "MB/FB",
                       "4" = "MHB",
                       "5" = "Spinal cord",
                       "6" = "Placode2",
                       "7" = "Blood/Vasc",
                       "8" = "Vasc/Heart",
                       "9" = "Neural crest",
                       "10" = "Placode3",
                       "11" = "Neuron",
                       "12" = "Muscle1",
                       "13" = "Eye",
                       "14" = "Placode4",
                       "15" = "r3/r5",
                       "16" = "Notochord",
                       "17" = "Muscle2",
                       "18" = "Endoderm",
                       "19" = "Kidney",
                       "20" = "Epidermis",
                       "21" = "Ciliated",
                       "22" = "Hatching gland")
seurat$Clusters <- Idents(seurat)
DimPlot(seurat, reduction = "wnn.umap", group.by ="Clusters", split.by = "orig.ident", label = T, repel = T) + scale_color_igv() + NoLegend()
```
```{r}
saveRDS(seurat, file = "RDSfiles/RFP.clustered.RDS")
```



```{r}
sessionInfo()
```

