---
title: "Notebooks to include in github"
author: "Rebecca O'Rourke"
date: "8/8/2022"
output: html_document
---

# 1. cellranger pipeline

Include cellranger.sh pipeline along with mkref.sh

# 2. workspace

## 2.1 Preprocssing
Preprocessing_and_QC.Rmd

## 2.2 Neural Subset
Neural_subsets/HB10/13/16/deab_hpf_neural_RNA-seq.Rmd -- just the portions of this to subset and reprocess.

## 2.3 Figures 1-3
Neural_subsets/ClusterNaming_and_plots_HB10/13/16.Rmd

Be sure to include extra plots from figures.
Be sure this has differential gene determination and write table.

### 2.3.1 Question for Charles
Do you want me to generate these figures completely in R (except for umap labelling and leaving space for zebrafish images of rhomobomere staining)? If so, do you want me to add A, B, C, etc... labels?

## 2.4 Figures 4 and 6
What notebooks did these come from

Need to include generation of DA motifs (check with Charles whether enriched or chromVar DA motifs) and plots of interest.

### 2.4.1 Question for Charles
Do you want me to generate these figures completely in R (except for umap labelling and leaving space for zebrafish images of rhomobomere staining)? If so, do you want me to add A, B, C, etc... labels?

## 2.5 Figure 5
Neural_subsets/HB10/13/16hpf_clustertree.Rmd (these are HB10/13/16hpf_clustertree_unrooted.png)

## 2.6 Figure 7
IntegrationOfIndependentNeuralSubsets/Integration_3WT_neural_subsets.Rmd -- add correct resolution clustering and save umap without labels and w/ legend at end

IntegrationOfIndependentNeuralSubsets/int3WT_clustertree.Rmd

### 2.6.1 new Fig 7 notebook
Once have final gene list for E and F (comparing gene expression per cell) generate new notebook that has:
* D: labelling of HB.1, HB.2 and HB.3 in integrated dataset
* E: Coexpression of sets of genes in umap (may only need third umap and simple legend for colors w/out color threshold)
* F: Barplots of sets of genes

## 2.7 Supplemental Figs S2, S3, S4
InitialExploration/ClusterNaming_and_plots_HB10/13/16.Rmd these are HB10/13/16hpf_combined2Plot.png

## 2.7.1 Question for Charles
Do you want these still as combined plots?  Do you want me to add A, B, C labels to them?