---
title: "HB13hpf neural Cluster Tree R Notebook"
output: github_document
---

# 1. libraries
```{r libraries, results=F}
suppressPackageStartupMessages({
  library(Seurat)
  library(Signac)
  library(dplyr)
  library(ggplot2)
  library(ggsci)
})
options(future.globals.maxSize = 4000 * 1024^2)
```

# 2. Read data
```{r readData}
HB13hpf <- readRDS("RDSfiles/HB13hpf_neural.RDS")
Idents(HB13hpf) <- "Clusters"
DimPlot(HB13hpf, reduction = "wnn.umap") + scale_color_igv()
```

# Build Cluster Tree
```{r BuildTree}
HB13hpf <- BuildClusterTree(HB13hpf, graph = "wsnn")
```

# Plot Cluster Tree

```{r PlotTree, fig.width=5, fig.height=3}
p <- PlotClusterTree(HB13hpf,direction = "rightwards")
p
```

```{r plot, fig.height=7, fig.width=7}
data.tree <- Tool(object = HB13hpf, slot = "BuildClusterTree")
png(filename = "../results/Fig5B_HB13hpf_clustertree_unrooted.png",width = 900, height = 900)
p1 <- ape::plot.phylo(x = data.tree,  use.edge.length = FALSE, cex = 0.8, type = "u")
p1
dev.off()
```


```{r sessionInfo}
sessionInfo()
```

