---
title: "Cluster Naming and plots neural HB16hpf R Notebook"
output: 
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. libraries and palette
```{r libraries, results=F}
suppressPackageStartupMessages({
  library(Seurat)
  library(org.Dr.eg.db)
  library(BSgenome.Drerio.UCSC.danRer11)
  library(Signac)
  library(knitr)
  library(kableExtra)
  library(dplyr)
  library(ggplot2)
  library(ggsci)
  library(limma)
  library(JASPAR2020)
  library(patchwork)
  library(TFBSTools)
  library(motifmatchr)
  library(harmony)
})
options(future.globals.maxSize = 4000 * 1024^2)
```

```{r mypal}
mypal <- pal_igv(palette = "default",alpha = 1)(35)
```


# 2. Read data
```{r readData}
seurat <- readRDS(file = "RDSfiles/HB16hpf_neural.RDS")
DefaultAssay(seurat) <- "SCT"
Idents(seurat) <- "wsnn_res.6"
DimPlot(seurat, reduction = "wnn.umap", label = T, repel = T) + scale_color_igv()
```

# 3. Rename Idents
```{r RenameIdents}
Idents(seurat) <- "wsnn_res.6"
seurat <- RenameIdents(seurat,
                       "0" = "Neuron",
                       "1" = "DorsNT & NC",
                       "2" = "CHB.1",
                       "3" = "MB.1",
                       "4" = "CHB.2",
                       "5" = "r2",
                       "6" = "r3",
                       "7" = "CHB.3",
                       "8" = "r6",
                       "9" = "SC.1",
                       "10" = "r5.1",
                       "11" = "MHB.1",
                       "12" = "r1",
                       "13" = "r5.2",
                       "14" = "r4",
                       "15" = "Ciliated",
                       "16" = "MB.2",
                       "17" = "MHB.2",
                       "18" = "FB",
                       "19" = "SC.2",
                       "20" = "SC.3",
                       "21" = "MHB.3",
                       "22" = "CHB.4")
levels(seurat) <- c("FB","MB.1","MB.2","MHB.1","MHB.2","MHB.3",
                    "r1","r2","r3","r4","r5.1","r5.2","r6","CHB.1","CHB.2",
                    "CHB.3","CHB.4","SC.1","SC.2","SC.3","DorsNT & NC","Neuron","Ciliated")
umapPlot <- DimPlot(seurat, reduction = "wnn.umap", pt.size = 2) + scale_color_igv() + guides(color = guide_legend(override.aes = list(size=4), ncol=1) )
umapPlot
seurat$Clusters <- Idents(seurat)
#ggsave(filename = "../results/Fig2_HB16hpf_umapPlot.png", plot = umapPlot)
```

```{r save}
saveRDS(seurat, file = "RDSfiles/HB16hpf_neural.RDS")
```

# 4. Find DE genes
```{r markers, results=F}
All.markers <- FindAllMarkers(seurat, only.pos = T, verbose = F)
write.table(All.markers, file = "../results/DataS2_Fig2_HB16hpf_markers.txt", sep = "\t", quote = F, col.names = NA)
```

```{r top5}
top5.pval <- All.markers %>% group_by(cluster) %>% top_n(n=-5, wt = p_val) %>% top_n(n=5, wt = avg_log2FC)
top5.pval
```

# 5. Plots
## 5.1 dotplot
```{r dotplot, fig.width=20, fig.height=5}
dotPlot <- DotPlot(seurat, features = unique(top5.pval$gene), dot.scale = 4) + RotatedAxis()
dotPlot
#ggsave(filename = "../results/Fig2_HB16hpf_dotPlot.png", plot = dotPlot)
```


```{r buildclustertree}
seurat <- BuildClusterTree(seurat, graph = "wsnn")
```

```{r plotclustertree, fig.width=5, fig.height=3}
p <- PlotClusterTree(seurat,direction = "rightwards")
p
```

```{r unrooted_vrs1, fig.height=7, fig.width=7}
data.tree <- Tool(object = seurat, slot = "BuildClusterTree")
pdf(file = "../results/Fig5_HB16hpf_clustertree_unrooted_vrs1.pdf")
p1 <- ape::plot.phylo(x = data.tree,  use.edge.length = FALSE, cex = 0.8, type = "u", 
                      align.tip.label = TRUE, label.offset = 0.5, lab4ut = "axial")
p1
dev.off()
```

```{r unrooted_vrs2, fig.height=7, fig.width=7}
pdf(file = "../results/Fig5_HB16hpf_clustertree_unrooted_vrs2.pdf")
p1 <- ape::plot.phylo(x = data.tree,  use.edge.length = FALSE, cex = 0.8, type = "u", 
                      align.tip.label = TRUE, label.offset = 0.5)
p1
dev.off()
```

## 5.3 Feature plots
```{r featureplot, fig.width=7, fig.height=7}
genePlots <- FeaturePlot(seurat, features = c("sox3","neurod4","zic2a","ntn1a"), reduction = "wnn.umap", max.cutoff = 2)
genePlots
#ggsave(filename = "../results/Fig2_HB16hpf_geneExpPlot.png", plot = genePlots)
```


## 5.4 combine umap, dotplot and heatmap
```{r combined, fig.height=10, fig.width=15}
combined <- (((umapPlot + 
      theme(legend.text = element_text(size = 20))) |
     (genePlots + plot_layout(guides = "collect"))) / 
       plot_spacer() /
    (dotPlot + 
       theme(axis.text.x = element_text(size = 10),
             axis.text.y = element_text(size = 12),
             legend.position = "bottom"))) +
    plot_layout(heights = c(1.5,0.1,1))
combined
ggsave(filename = "../results/Fig2_HB16hpf_combinedPlot.png", plot = combined)
```


```{r sessionInfo}
sessionInfo()
```