---
title: "HB13hpf WT vs DEAB R Notebook"
output:
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. libraries and palette
```{r libraries, results=F}
suppressPackageStartupMessages({
  library(Seurat)
  library(org.Dr.eg.db)
  library(BSgenome.Drerio.UCSC.danRer11)
  library(Signac)
  library(knitr)
  library(kableExtra)
  library(dplyr)
  library(ggplot2)
  library(ggsci)
  library(limma)
  library(JASPAR2020)
  library(patchwork)
  library(TFBSTools)
  library(motifmatchr)
  library(harmony)
})
options(future.globals.maxSize = 4000 * 1024^2)
```

```{r mypal}
mypal <- pal_igv(palette = "default",alpha = 1)(35)
```

# 2. Read data
```{r readData}
HB10hpf <- readRDS(file = "RDSfiles/HB10hpf_neural.RDS")
DefaultAssay(HB10hpf) <- "SCT"
Idents(HB10hpf) <- "Clusters"

WTplusDEAB <- readRDS(file = "RDSfiles/HB13.WT.DEAB.neural.refMap.int.RDS")
```

# 3. Plots
```{r dimplot1}
DimPlot(HB10hpf, reduction = "wnn.umap", label = T, repel = T) + scale_color_igv() + NoLegend()
```

```{r featureplot}
rarabPlot <- FeaturePlot(HB10hpf, features = "rarab",reduction = "wnn.umap", max.cutoff = 2.1)
rarabPlot
crabp2aPlot <- FeaturePlot(HB10hpf, features = "crabp2a",reduction = "wnn.umap", max.cutoff = 2.1)
crabp2aPlot
```

```{r featureplot, fig.width=4, fig.height=8}
vlnPlot_10hpf <- VlnPlot(HB10hpf, features = c("rarab","crabp2a"), cols = mypal, ncol = 1)
vlnPlot_10hpf
```

```{r}
split_umap <- DimPlot(WTplusDEAB, reduction = "ref.umap", group.by =  "predicted.Clusters", split.by = "orig.ident") + 
  scale_color_igv()  + ggtitle("")
split_umap
```

```{r}
umap <- DimPlot(WTplusDEAB, reduction = "ref.umap", group.by =  "predicted.Clusters") + scale_color_igv() + ggtitle("")
umap
```

# Fig 7 combined plots

```{r, fig.width=20, fig.height=5}
combined1 <- plot_spacer() + (rarabPlot / crabp2aPlot) + vlnPlot_10hpf + (split_umap + NoLegend()) + umap + 
  plot_layout(widths = c(0.05,0.5,1.1,1.8,1))
combined1
ggsave(filename = "../results/Fig7_10hpf_plus_WTvsDEAB_combinedPlot1.png", plot = combined1)
```

```{r, fig.width=20, fig.height=10}
combined2 <- (plot_spacer() + (rarabPlot / crabp2aPlot) + vlnPlot_10hpf + split_umap + plot_layout(widths = c(0.05,0.5,1.1,1.8))) / 
  (umap + plot_spacer() + plot_layout(widths = c(1,3.5))) 
combined2
ggsave(filename = "../results/Fig7_10hpf_plus_WTvsDEAB_combinedPlot2.png", plot = combined2)
```

```{r}
sessionInfo()
```

