---
title: "Figure 6 r2 and r3 genes barplots R Notebook"
author: "Rebecca O'Rourke"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1 Libraries
```{r, results=F}
suppressPackageStartupMessages({
  library(Seurat)
  library(org.Dr.eg.db)
  library(BSgenome.Drerio.UCSC.danRer11)
  library(Signac)
  library(knitr)
  library(kableExtra)
  library(dplyr)
  library(ggplot2)
  library(ggsci)
  library(limma)
  library(JASPAR2020)
  library(patchwork)
  library(TFBSTools)
  library(motifmatchr)
  library(AnnotationHub)
  library(harmony)
})
options(future.globals.maxSize = 4000 * 1024^2)
```

```{r mypal}
mypal <- pal_igv(palette = "default",alpha = 1)(35)
```

# Read data
Subsetting the integrated seurat object to obtain HB13hpf r2 or r3 cells fails.  This could likely be fixed with update of Seurat but that would affect UMAP so instead will use individual HB13hpf and HB10hpf Seurat Objects for r2, r3 and HB.1 cells.
```{r}
HB10hpf <- readRDS(file = "RDSfiles/HB10hpf_neural.RDS")
HB13hpf <- readRDS(file = "RDSfiles/HB13hpf_neural.RDS")
```


# Bar plots cell counts expressing genes
```{r}
r2_genes <- c("ptprn2","efnb3b","chl1b","si:ch211-286o17.1","cyp26c1","vgll3","plxna2","ppap2d","zgc:174888","tgfbr2b","crim1",
              "bmpr1ba","cxcl12a","LHFPL6")
r3_genes <- c("epha4a","sema3fb","egr2b","brinp2","nab2","egr2a","timp2b","myo1cb","nab1b","si:ch211-191i18.2",
              "cbarpb","nlgn4xa","grm4","adprhl2","slc1a6")
```

```{r}
Idents(HB13hpf) <- "Clusters"
HB13.r2.r2cells <- subset(HB13hpf, idents = "r2", features = r2_genes)
df.HB13.r2.r2 <- as.data.frame(t(GetAssayData(HB13.r2.r2cells, slot = "data", assay = "SCT")))
df.HB13.r2.r2

HB13.r2.r3cells <- subset(HB13hpf, idents = "r2", features = r3_genes)
df.HB13.r2.r3 <- as.data.frame(t(GetAssayData(HB13.r2.r3cells, slot = "data", assay = "SCT")))
df.HB13.r2.r3

HB13.r3.r2cells <- subset(HB13hpf, idents = "r3", features = r2_genes)
df.HB13.r3.r2 <- as.data.frame(t(GetAssayData(HB13.r3.r2cells, slot = "data", assay = "SCT")))
df.HB13.r3.r2

HB13.r3.r3cells <- subset(HB13hpf, idents = "r3", features = r3_genes)
df.HB13.r3.r3 <- as.data.frame(t(GetAssayData(HB13.r3.r3cells, slot = "data", assay = "SCT")))
df.HB13.r3.r3
```


```{r}
HB13.r2.r2counts <- as.data.frame(colSums(df.HB13.r2.r2 > 0)) %>%
  dplyr::rename(r2_count = 1) %>%
  tibble::rownames_to_column(var = "gene") %>%
  arrange(desc(r2_count)) %>% 
  mutate(r2_percent_cells = r2_count/nrow(HB13.r2.r2cells@meta.data)) %>%
  mutate(gene = forcats::fct_reorder(gene, r2_count))
HB13.r2.r2counts
```

```{r}
r2_order <- levels(HB13.r2.r2counts$gene)

HB13.r3.r3counts <- as.data.frame(colSums(df.HB13.r3.r3 > 0)) %>%
  dplyr::rename(r3_count = 1) %>%
  tibble::rownames_to_column(var = "gene")  %>%
  arrange(desc(r3_count)) %>% 
  mutate(r3_percent_cells = r3_count/nrow(HB13.r3.r3cells@meta.data)) %>%
  mutate(gene = forcats::fct_reorder(gene, r3_count))
HB13.r3.r3counts
```

```{r}
r3_order <- levels(HB13.r3.r3counts$gene)

HB13.r2.r3counts <- as.data.frame(colSums(df.HB13.r2.r3 > 0)) %>%
  dplyr::rename(r2_count = 1) %>%
  tibble::rownames_to_column(var = "gene")  %>%
  mutate(r2_percent_cells = r2_count/nrow(HB13.r2.r3cells@meta.data)) %>%
  mutate(gene = forcats::fct_relevel(gene, r3_order))
HB13.r2.r3counts
```

```{r}
HB13.r3.r2counts <- as.data.frame(colSums(df.HB13.r3.r2 > 0)) %>%
  dplyr::rename(r3_count = 1) %>%
  tibble::rownames_to_column(var = "gene") %>%
  mutate(r3_percent_cells = r3_count/nrow(HB13.r3.r2cells@meta.data)) %>%
  mutate(gene = forcats::fct_relevel(gene, r2_order))
HB13.r3.r2counts
```

```{r}
p3 <- ggplot(HB13.r2.r2counts, aes(y=-r2_percent_cells, x=gene)) + 
  geom_bar(stat="identity", fill = mypal[1]) +
  coord_flip() +
  theme_classic() +
  scale_x_discrete(name = "", position = "top") +     # x axis (before coord_flip) on opposite side
  scale_y_continuous(name = "r2 (HB13hpf)",
                     breaks = seq(0, -1, by = -0.20),  # y axis values (before coord_flip) 
                     labels = seq(0,  1, by =  0.20),
                     limits = c(-1,0))
p4 <- ggplot(HB13.r2.r3counts, aes(y=r2_percent_cells, x=gene)) + 
  geom_bar(stat="identity", fill = mypal[2]) +
  coord_flip() +
  theme_classic() + 
  theme(axis.title.y = element_blank()) +
  scale_y_continuous(name = "r2 (HB13hpf)",
                     breaks = seq(0, 1, by = 0.20),
                     limits = c(0,1))
p5 <- ggplot(HB13.r3.r2counts, aes(y=-r3_percent_cells, x=gene)) + 
  geom_bar(stat="identity", fill = mypal[1]) +
  coord_flip() +
  theme_classic() +
  scale_x_discrete(name = "", position = "top") +     # x axis (before coord_flip) on opposite side
  scale_y_continuous(name = "r3 (HB13hpf)",
                     breaks = seq(0, -1, by = -0.20),  # y axis values (before coord_flip) 
                     labels = seq(0,  1, by =  0.20),
                     limits = c(-1,0))
p6 <- ggplot(HB13.r3.r3counts, aes(y=r3_percent_cells, x=gene)) + 
  geom_bar(stat="identity", fill = mypal[2]) +
  coord_flip() +
  theme_classic() + 
  theme(axis.title.y = element_blank()) +
  scale_y_continuous(name = "r3 (HB13hpf)",
                     breaks = seq(0, 1, by = 0.20),
                     limits = c(0,1))
p3 + p4 + p5 + p6 + plot_layout(ncol = 4)
```

```{r}
Idents(HB10hpf) <- "Clusters"
HB.1.r2cells <- subset(HB10hpf, idents = "HB.1", features = r2_genes)
df.HB1.r2 <- as.data.frame(t(GetAssayData(HB.1.r2cells, slot = "data", assay = "SCT")))
df.HB1.r2

HB.1.r3cells <- subset(HB10hpf, idents = "HB.1", features = r3_genes)
df.HB1.r3 <- as.data.frame(t(GetAssayData(HB.1.r3cells, slot = "data", assay = "SCT")))
df.HB1.r3
```

```{r}
HB.1.r2counts <- as.data.frame(colSums(df.HB1.r2 > 0)) %>%
  dplyr::rename(HB.1_count = 1) %>%
  tibble::rownames_to_column(var = "gene") %>%
  arrange(desc(HB.1_count)) %>% 
  mutate(HB.1_percent_cells = HB.1_count/nrow(HB.1.r2cells@meta.data)) %>%
  mutate(gene = forcats::fct_relevel(gene, r2_order))
HB.1.r2counts
```

```{r}
HB.1.r3counts <- as.data.frame(colSums(df.HB1.r3 > 0)) %>%
  dplyr::rename(HB.1_count = 1) %>%
  tibble::rownames_to_column(var = "gene")  %>%
  tibble::add_row(gene = "egr2a", HB.1_count = 0) %>% ## egr2a not in HB10hpf dataset so adding to df, cell count = 0
  arrange(desc(HB.1_count)) %>% 
  mutate(HB.1_percent_cells = HB.1_count/nrow(HB.1.r3cells@meta.data)) %>%
  mutate(gene = forcats::fct_relevel(gene, r3_order))
HB.1.r3counts
```

```{r}
p1 <- ggplot(HB.1.r2counts, aes(y=-HB.1_percent_cells, x=gene)) + 
  geom_bar(stat="identity", fill = mypal[1]) +
  coord_flip() +
  theme_classic() +
  scale_x_discrete(name = "", position = "top") + # x axis (before coord_flip) on opposite side
  scale_y_continuous(name = "HB.1 (HB10hpf)",
                     breaks = seq(0, -1, by = -0.20),  # y axis values (before coord_flip) 
                     labels = seq(0,  1, by =  0.20),
                     limits = c(-1,0))
p2 <- ggplot(HB.1.r3counts, aes(y=HB.1_percent_cells, x=gene)) + 
  geom_bar(stat="identity", fill = mypal[2]) +
  coord_flip() +
  theme_classic() +
  theme(axis.title.y = element_blank()) +
  scale_y_continuous(name = "HB.1 (HB10hpf)",
                     breaks = seq(0, 1, by = 0.20),
                     limits = c(0,1))
  
p1 + p2
```

```{r}
barplots <- (p1 + p2) / (p3 + p4) / (p5 + p6)
barplots
saveRDS(barplots, file = "../results/r2_r3_gene_barplots.RDS")
```

```{r}
sessionInfo()
```

