---
title: "Expression of vgll3, nab1b and egr2b in HB.1 cells in HB10hpf R Notebook"
output: html_notebook
---


# 1 libraries
```{r, results=F}
suppressPackageStartupMessages({
  library(Seurat)
  library(Signac)
  library(knitr)
  library(kableExtra)
  library(dplyr)
  library(ggplot2)
  library(ggalluvial)
  library(ggsci)
  library(tidyr)
  library(tidyverse)
  library(patchwork)
  library(dittoSeq)
  library(ComplexHeatmap)
  library(JASPAR2020)
  library(TFBSTools)
  library(motifmatchr)
  library(org.Dr.eg.db)
  library(BSgenome.Drerio.UCSC.danRer11)
})
options(future.globals.maxSize = 4000 * 1024^2)
```

# 2 read data

```{r}
HB10hpf <- readRDS(file = "RDSfiles/HB10hpf_neural.RDS")
```

# 4. Expression of vgll3, egr2b and nab1b by cell in HB.1

## 4.1 HB10hpf HB.1 data
```{r}
HB.1cells <- subset(HB10hpf, idents = "HB.1", features = c("vgll3","egr2b","nab1b"))
df.HB1 <- as.data.frame(t(GetAssayData(HB.1cells, slot = "data", assay = "SCT")))

HB1.vgll3 <- sum(df.HB1$vgll3 > 0 & df.HB1$egr2b == 0 & df.HB1$nab1b == 0) 
HB1.egr2b <- sum(df.HB1$vgll3 == 0 & df.HB1$egr2b > 0 & df.HB1$nab1b == 0) 
HB1.nab1b <- sum(df.HB1$vgll3 == 0 & df.HB1$egr2b == 0 & df.HB1$nab1b > 0) 
HB1.vgll3.egr2b <- sum(df.HB1$vgll3 > 0 & df.HB1$egr2b > 0 & df.HB1$nab1b == 0) 
HB1.vgll3.nab1b <- sum(df.HB1$vgll3 > 0 & df.HB1$egr2b == 0 & df.HB1$nab1b > 0) 
HB1.vgll3.egr2b.nab1b <- sum(df.HB1$vgll3 > 0 & df.HB1$egr2b > 0 & df.HB1$nab1b > 0) 
HB1.egr2b.nab1b <- sum(df.HB1$vgll3 == 0 & df.HB1$egr2b > 0 & df.HB1$nab1b > 0) 
HB1.none <- sum(df.HB1$vgll3 == 0 & df.HB1$egr2b == 0 & df.HB1$nab1b == 0)

# create a dataset
rhombomere <- c("HB1","HB1","HB1","HB1")
# condition <- c("+vgll3/-egr2b/-nab1b","-vgll3/+egr2b/-nab1b","-vgll3/-egr2b/+nab1b","+vgll3/+egr2b/-nab1b",
#                "+vgll3/-egr2b/+nab1b","-vgll3/+egr2b/+nab1b","+vgll3/+egr2b/+nab1b","-vgll3/-egr2b/-nab1b")
vgll3.egr2b.nab1b <- c("+/-/-","-/+/-","-/-/+","+/+/-",
               "+/-/+","-/+/+","+/+/+","-/-/-")
count <- c(HB1.vgll3,HB1.egr2b,HB1.nab1b,HB1.vgll3.egr2b,
           HB1.vgll3.nab1b,HB1.egr2b.nab1b,HB1.vgll3.egr2b.nab1b,HB1.none)
#HB.1data <- data.frame(rhombomere,condition,count)
HB.1data <- data.frame(rhombomere,vgll3.egr2b.nab1b,count)
HB.1data
```

```{r}
vgll3_egr2b_nab1b_barplot <- ggplot(HB.1data, aes(fill=vgll3.egr2b.nab1b, y=count, x=rhombomere)) + 
    geom_bar(stat="identity") + ylim(0,60) +
    geom_text(data = subset(HB.1data, count !=0),aes(label = count), position = position_stack(vjust = 0.5), 
              color = c(rep("black",6),"white","black")) +
  scale_fill_manual(values = c("grey","red","yellow","orange","blue","purple","green","black")) +
  theme_classic() + theme(axis.title.x = element_blank()) + guides(fill=guide_legend(title="vgll3/egr2b/nab1b"))
vgll3_egr2b_nab1b_barplot
```
```{r}
saveRDS(vgll3_egr2b_nab1b_barplot, file = "../results/vgll3_egr2b_nab1b_barplot.RDS")
```

```{r}
sessionInfo()
```

